EXP_NAME: 'SOME_RANDOM_NAME'
RNG_SEED: 1
GPU_ID: '3'
DATASET:
  NAME: CIFAR100 
  ROOT_DIR: 'data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'horizontalflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'adam'
  BASE_LR: 0.00005
  LR_POLICY: steps
  STEPS: [0] #[0, 30, 60, 90]
  MAX_EPOCH: 100
  MOMENTUM: 0
  NESTEROV: False
  WEIGHT_DECAY: 0
  GAMMA: 0
TRAIN:
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  EVAL_PERIOD: 100
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  BUDGET_SIZE: 5000
  SAMPLING_FN: 'random'
  INIT_RATIO: 0.1
  MAX_ITER: 10